# This file generates the GitHub Actions matrix.
---
include:
  # mac_onishi
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DZMK_CONFIG=config/mac_onishi
    artifact-name: toucan_left_mac_onishi
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    cmake-args: -DZMK_CONFIG=config/mac_onishi
    artifact-name: toucan_right_mac_onishi
  - board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DZMK_CONFIG=config/mac_onishi
    artifact-name: settings_reset_mac_onishi

  # mac_qwerty
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DZMK_CONFIG=config/mac_qwerty
    artifact-name: toucan_left_mac_qwerty
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    cmake-args: -DZMK_CONFIG=config/mac_qwerty
    artifact-name: toucan_right_mac_qwerty
  - board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DZMK_CONFIG=config/mac_qwerty
    artifact-name: settings_reset_mac_qwerty

  # win_onishi
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DZMK_CONFIG=config/win_onishi
    artifact-name: toucan_left_win_onishi
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    cmake-args: -DZMK_CONFIG=config/win_onishi
    artifact-name: toucan_right_win_onishi
  - board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DZMK_CONFIG=config/win_onishi
    artifact-name: settings_reset_win_onishi

  # win_qwerty
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DZMK_CONFIG=config/win_qwerty
    artifact-name: toucan_left_win_qwerty
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    cmake-args: -DZMK_CONFIG=config/win_qwerty
    artifact-name: toucan_right_win_qwerty
  - board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DZMK_CONFIG=config/win_qwerty
    artifact-name: settings_reset_win_qwerty
