---
include:
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: toucan_left_mac_onishi
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    artifact-name: toucan_right_mac_onishi
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_mac_onishi
